/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "example.h"

bool_t
xdr_filekind (XDR *xdrs, filekind *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_filetype (XDR *xdrs, filetype *objp)
{
	register int32_t *buf;

	 if (!xdr_filekind (xdrs, &objp->kind))
		 return FALSE;
	switch (objp->kind) {
	case TEXT:
		break;
	case DATA:
		 if (!xdr_string (xdrs, &objp->filetype_u.creator, MAXNAMELEN))
			 return FALSE;
		break;
	case EXEC:
		 if (!xdr_string (xdrs, &objp->filetype_u.interpretor, MAXNAMELEN))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_file (XDR *xdrs, file *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->filename, MAXNAMELEN))
		 return FALSE;
	 if (!xdr_filetype (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->owner, MAXUSERNAME))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, MAXFILELEN))
		 return FALSE;
	return TRUE;
}
