/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "liczby.h"

bool_t
xdr_request (XDR *xdrs, request *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->numbers.numbers_val, (u_int *) &objp->numbers.numbers_len, MAXNUMBERS,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_response (XDR *xdrs, response *objp)
{
	register int32_t *buf;

	 if (!xdr_bool (xdrs, &objp->error))
		 return FALSE;
	switch (objp->error) {
	case 0:
		 if (!xdr_int (xdrs, &objp->response_u.suma))
			 return FALSE;
		break;
	case 1:
		 if (!xdr_string (xdrs, &objp->response_u.errmsg, 3))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}
